# Default values for service-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

groupName: gpu-service-groups
publicIP: "0.0.0.0"
publicDomain: ""

proxyNodes:
- nodeName: slave4
  ip: 172.22.96.186
- nodeName: slave5
  ip: 172.22.96.192

serviceProxyImage:
  repository: harbor.172.22.96.178.nip.io/system_containers/tenx-proxy
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v5.6.0-20231019"

exporterImage:
  repository: harbor.172.22.96.178.nip.io/system_containers/haproxy-exporter
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.13.0"

